language: scala
scala:
  - 2.12.2
jdk: oraclejdk8
script:
  - sbt "^scripted"
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
notifications:
  email:
    recipients:
      - yuizalp@gmail.com
  on_success: always
